import { useMemo, useState } from 'react'
import { ArrowRight, CheckCircle2, ExternalLink, FileText, Globe2, Info, Link as LinkIcon, ListFilter, Search, ShieldCheck, UserRound, Vote } from 'lucide-react'
import { parties, sources, topics } from './data/parties.js'

function Header({ activeParty, setActiveParty }) {
  return <header className="topbar"><a href="#" className="brand" onClick={() => setActiveParty(null)}><div className="brandBadge">Í26</div><div><strong>Ísafjörður 2026</strong><span>Stefnuskrár í einum stað</span></div></a><nav><a href="#flokkar">Flokkar</a><a href="#samanburdur">Samanburður</a><a href="#heimildir">Heimildir</a></nav><button className="ghostButton" onClick={() => setActiveParty(activeParty ? null : parties[0].id)}><Vote size={18}/>{activeParty ? 'Forsíða' : 'Skoða flokk'}</button></header>
}
function Hero() {
  return <section className="hero"><div className="heroContent"><p className="eyebrow"><ShieldCheck size={16}/> Óháð yfirlit í vinnslu</p><h1>Berðu saman stefnur flokkanna í Ísafjarðarbæ.</h1><p>Vefurinn safnar saman stefnuskrám, framboðslistum og heimildum á einn stað svo íbúar geti séð muninn á áherslum flokkanna.</p><div className="heroActions"><a className="primaryButton" href="#samanburdur">Skoða samanburð <ArrowRight size={18}/></a><a className="secondaryButton" href="#flokkar">Velja flokk</a></div></div><div className="heroStats"><div><strong>5</strong><span>framboðslistar</span></div><div><strong>{topics.length}</strong><span>málaflokkar</span></div><div><strong>{sources.length}</strong><span>heimildatenglar</span></div></div></section>
}
function PartyCards({ setActiveParty }) {
  return <section id="flokkar" className="partyStrip">{parties.map(p => <article className="partyCard" key={p.id}><div className="partyLetter" style={{color:p.color,background:p.lightColor}}>{p.letter}</div><div className="partyCardBody"><p className="listName">{p.list}</p><h2>{p.name}</h2><span className="pill" style={{color:p.color,background:p.lightColor}}>{p.status}</span><button onClick={() => setActiveParty(p.id)}>Skoða nánar <ArrowRight size={16}/></button></div></article>)}</section>
}
function ComparisonTable({ query }) {
  const visibleTopics = useMemo(() => { const q = query.toLowerCase().trim(); return q ? topics.filter(t => t.name.toLowerCase().includes(q)) : topics }, [query])
  return <section id="samanburdur" className="panel comparisonPanel"><div className="panelHeader"><div><p className="eyebrow"><ListFilter size={15}/> Samanburður</p><h2>Málaflokkar eftir flokkum</h2><p>Stutt lýsing á áherslum hvers flokks eftir málaflokki. Textinn er tilbúinn til frekari yfirferðar og tilvitnana úr frumheimildum.</p></div></div><div className="comparisonGrid"><div className="gridHead topicHead">Málaflokkur</div>{parties.map(p => <div className="gridHead partyHead" key={p.id}><strong style={{color:p.color}}>{p.letter}</strong><span>{p.shortName}</span></div>)}{visibleTopics.map(t => <React.Fragment key={t.id}><div className="topicName">{t.name}</div>{parties.map(p => <div className="topicText" key={p.id+t.id}>{p.topics[t.id]}</div>)}</React.Fragment>)}</div></section>
}
import React from 'react'
function PartyDetail({ party, setActiveParty }) {
  return <section className="partyDetail"><button className="backButton" onClick={() => setActiveParty(null)}>← Til baka á forsíðu</button><div className="detailHero" style={{'--party':party.color,'--light':party.lightColor}}><div className="bigLetter">{party.letter}</div><div><p className="eyebrow">{party.list}</p><h1>{party.name}</h1><p>{party.summary}</p><div className="detailLinks"><a href={party.website} target="_blank" rel="noreferrer"><Globe2 size={17}/> Heimasíða</a>{party.manifestoUrl ? <a href={party.manifestoUrl} target="_blank" rel="noreferrer"><FileText size={17}/> Stefnuskrá</a> : <span><Info size={17}/> Stefnuskrá vantar</span>}{party.candidatesUrl ? <a href={party.candidatesUrl} target="_blank" rel="noreferrer"><UserRound size={17}/> Frambjóðendur</a> : <span><Info size={17}/> Frambjóðendur vantar</span>}</div></div></div><div className="detailGrid"><article className="panel"><h2>Helstu áherslur</h2><ul className="checkList">{party.keyIssues.map(i => <li key={i}><CheckCircle2 size={18}/> {i}</li>)}</ul></article><article className="panel"><h2>Frambjóðendur</h2><ul className="simpleList">{party.candidates.map(c => <li key={c}>{c}</li>)}</ul><p className="note">Nöfn frambjóðenda má bæta beint inn þegar við höfum farið yfir framboðslistana.</p></article></div><article className="panel"><h2>Stefna eftir málaflokkum</h2><div className="topicCards">{topics.map(t => <div className="miniTopic" key={t.id}><h3>{t.name}</h3><p>{party.topics[t.id]}</p></div>)}</div></article></section>
}
function Sources() {
  return <section id="heimildir" className="panel sourcesPanel"><div className="panelHeader"><div><p className="eyebrow"><LinkIcon size={15}/> Heimildir</p><h2>Frumheimildir og tenglar</h2><p>Allar upplýsingar eiga að vera rekjanlegar í stefnuskrár, heimasíður eða framboðslista.</p></div></div><div className="sourceList">{sources.map(s => <a href={s.url} target="_blank" rel="noreferrer" key={s.url}><span>{s.label}</span><ExternalLink size={16}/></a>)}</div></section>
}
export default function App() {
  const [activePartyId, setActiveParty] = useState(null)
  const [query, setQuery] = useState('')
  const activeParty = parties.find(p => p.id === activePartyId)
  return <div className="site"><Header activeParty={activePartyId} setActiveParty={setActiveParty}/>{activeParty ? <main className="pageWrap"><PartyDetail party={activeParty} setActiveParty={setActiveParty}/></main> : <main><Hero/><PartyCards setActiveParty={setActiveParty}/><section className="tools pageWrap"><div className="searchBox"><Search size={18}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Leita að málaflokki, t.d. húsnæði, skólar eða fjármál..."/></div><div className="infoBox"><Info size={18}/><span>Gögnin eru í vinnslu. Næsta skref er að setja inn beinar tilvitnanir og nöfn frambjóðenda.</span></div></section><div className="pageWrap layoutGrid"><ComparisonTable query={query}/><aside className="sideStack"><article className="panel"><p className="eyebrow">Staða gagna</p><h2>Hvað er komið?</h2><ul className="statusList"><li><CheckCircle2 size={18}/> Heimasíður allra flokka</li><li><CheckCircle2 size={18}/> Stefnuskrár B, C, D og S</li><li><CheckCircle2 size={18}/> Frambjóðendatenglar þar sem til eru</li><li><Info size={18}/> M-lista vantar stefnuskrá/frambjóðendur</li></ul></article><article className="panel"><p className="eyebrow">Næst</p><h2>Til að klára</h2><p>Lesa PDF-skjölin, taka beinar tilvitnanir, setja inn frambjóðendanöfn og bæta við kosningaprófi.</p></article></aside></div><div className="pageWrap"><Sources/></div></main>}</div>
}
